perfreports:
  level: process
  text: false

monitoring:
  default_interval: 1.0

export_vars:
  perfdata: perfdata_df
  cell_history: cell_history_df

loaded_vars:
  perfdata: loaded_perfdata_df
  cell_history: loaded_cell_history_df

visualizer_backend: matplotlib
