name: Linter

on:
  workflow_run:
    workflows: [Formatter]
    types: [completed]
    branches:
      - '*'
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - uses: py-actions/flake8@v2
        with:
          ignore: "E203"
          path: "jumper_extension"
