name: Linter

on:
  workflow_run:
    workflows: [Formatter]
    types: [completed]

jobs:
  linter:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        run: flake8 --extend-ignore=E203 jumper_extension
